### PR TITLE
chore: exclude windows from pr build

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Also fix mergify config, which started ignoring the E2E test requirement due to a regression from my last PR.

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Review by hasanaburayyan — APPROVED** [review]

**Review by Chriscbr — APPROVED** [review]

**Comment by eladb** [comment]
What's the rationale?

**Comment by Chriscbr** [comment]
I think we decided in Mark's last PR that E2E tests would only be run on all platforms if a `pr/e2e-full` label is added, and this was a bug

**Comment by MarkMcCulloh** [comment]
> Can you link to the discussion? Curious about the rationale? Is it cost?

Time, the same rationale to add sharding. 
We still make sure to avoid publishing broken code while maintaining "fast" PRs, at the cost of rarely breaking main.

**Comment by eladb** [comment]
> > Can you link to the discussion? Curious about the rationale? Is it cost?
> 
> 
> 
> Time, the same rationale to add sharding. 
> 
> We still make sure to avoid publishing broken code while maintaining "fast" PRs, at the cost of rarely breaking main (specifically for windows and mac).

Let's make sure to include rationale in PR description for posterity

**Pull request merged**
