### PR TITLE
docs(docs): delete standard lib docs from /docs

### PR DESCRIPTION
**Pull request by boyney123**
Think this may have been missed, the standard libs are now in `/docs/api` and rendered here on the website https://www.winglang.io/docs/api/standard-library

As you can see they are still in /learn, this will remove them from /learn.
image 

## Checklist

- [x ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Comment by ainvoner** [comment]
@boyney123 check out the mutation commit... it reverted the whole thing

**Comment by MarkMcCulloh** [comment]
The sdk docs are copied from libs/wingsdk during the build process, see the script [here](https://github.com/winglang/wing/blob/main/libs/wingsdk/scripts/docgen.mts)


To move the files, it should be sufficient to change [this path](https://github.com/winglang/wing/blob/main/libs/wingsdk/scripts/docgen.mts#L20), delete the files you deleted in the first commit, and the run that script or (`turbo docgen -F sdk`)

**Comment by boyney123** [comment]
Think some merge/updates went wrong going to clean this up, and just create new branch, not sure what's happened here!

**Comment by boyney123** [comment]
Opened here https://github.com/winglang/wing/pull/6907

**Pull request closed without merging**
