### PR TITLE
fix(cli): not to show 1 test when no tests are in the file

### LINKED ISSUE #5852: Running wing test on an empty wing file shows 1 passed test
### I tried this:

Created an empty wing file without tests.

Run `wing test main.w`.

### This happened:

```
pass ─ main.wsim (no tests)


Tests 1 passed (1)
Test Files 1 passed (1)
Duration 0m0.31s
```

### I expected this:

```
pass ─ main.wsim (no tests)


Tests 0 passed (0)
Test Files 1 passed (1)
Duration 0m0.31s
```

### Is there a workaround?

_No response_

### Anything else?

image
npm 

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
This is to fix an issue that caused `wing test` against an empty `some_file_name.w` file shows `Tests 1 passed (1)`.

See the issue #5852 for details.

Solution:
Instead of adding a dummy pass message, the function now returns early with a predefined message when there's no test case to avoid confusion later.

And I don't think it would need full E2E tests?

I am still exploring how to add test for this new test system behavior. Will mark the PR as ready after adding/updating test for it.

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

Resolves #5852

### CODE REVIEW

**Comment by eladb** [comment]
@ChihweiLHBird thanks for this! Do you mind adding a few more details in the description on the bug itself and how this will look like after the fix?

**Comment by ChihweiLHBird** [comment]
Hi @eladb, thanks for the suggestion! This is just a draft PR and I will mark it as ready after adding those things.

Let me know if you have any feedback or anything, for example whether this is the right way to fix it, thanks! ^_^

**Comment by ChihweiLHBird** [comment]
Hey @eladb @Chriscbr, I think this PR is ready for reviews. And the CI reported a rate limiting error, should we try a re-run?

**Comment by eladb** [comment]
@ChihweiLHBird let us know if you need any help

**Comment by ChihweiLHBird** [comment]
@eladb Does it look good to you?

**Comment by skyrpex** [comment]
Thanks for your contribution! I'm having a look at the CI problem here 👀 ...

**Review by skyrpex — APPROVED** [review]

**Pull request merged**
