### PR TITLE
feat(sdk): use granular permissions for `tf-gcp` platform

### LINKED ISSUE #4702: Least privilege access for inflight operations on `tf-gcp` target
### Feature Spec

The current approach for the `tf-gcp` target utilizes GCP's [predefined roles](https://cloud.google.com/iam/docs/understanding-roles) to grant permissions to the Cloud Function for executing inflight operations, as evident from [this reference](https://github.com/winglang/wing/blob/5f6a31d348b198f70983d0eef65719ddc0604ef5/libs/wingsdk/src/target-tf-gcp/function.ts#L29C1-L34C2).

This configuration, however, isn't ideal. A better approach would be to adopt a methodology similar to the one implemented for the `tf-aws` target, where permissions are managed through a separate [permissions file](https://github.com/winglang/wing/blob/main/libs/wingsdk/src/shared-aws/permissions.ts). Such a strategy would let us craft a custom role and designate precise permissions for each distinct operation. Taking the `cloud.Bucket` resource as an example, we could granularly assign permissions like:

- `storage.objects.create`
- `storage.objects.delete`
- `storage.objects.get`
- `storage.objects.list`
- `storage.objects.update`

### Use Cases

Follow security best practices.

### Implementation Notes

_No response_

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

### LINKED ISSUE #5235: many bucket tests are not passing on tf-gcp
### I tried this:

```
wing test -t tf-gcp examples/tests/sdk_tests/bucket/*.test.w
```

### This happened:

```
Results:
    ✓ bucket/aws-bucket.test.w
    ✓ bucket/add_file.test.w
    ✓ bucket/add_object.test.w
    ✓ bucket/try_delete.test.w
    ✓ bucket/load_test.test.w
    × bucket/try_get_json.test.w
    × bucket/delete.test.w
    × bucket/exists.test.w
    × bucket/try_get.test.w
    × bucket/put.test.w
    × bucket/put_json.test.w
    × bucket/bucket_list.test.w
    × bucket/public_url.test.w
    ? bucket/metadata.test.w
    ? bucket/copy.test.w
    ? bucket/events.test.w
    ? bucket/signed_url.test.w
 
Errors:
At bucket/try_get_json.test.w
Error: Error while invoking the function handler-c86d56de:
Failed to put JSON object. (key=file1.json)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 16)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/delete.test.w
Error: Error while invoking the function handler-c83af1ae:
Failed to put JSON object. (key=file1.json)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 3)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/exists.test.w
Error: Error while invoking the function handler-c80b6081:
Failed to put object. (key=test1.txt)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 5)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/try_get.test.w
Error: Error while invoking the function handler-c83dfd4e:
Failed to put object. (key=test1.txt)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 14)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/put.test.w
Error: Error while invoking the function handler-c89ffda6:
Failed to put object. (key=test1.txt)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 10)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/put_json.test.w
Error: Error while invoking the function handler-c8382d17:
Failed to put JSON object. (key=test1.txt)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 13)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/bucket_list.test.w
Error: Error while invoking the function handler-c888d6b1:
Failed to put JSON object. (key=file1.json)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 2)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/public_url.test.w
Error: Error while invoking the function handler-c8a170cc:
Failed to put object. (key=file1.txt)
    at FunctionClient._invokeLocally (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:31:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionClient.invokeWithLogs (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/function.inflight.js:72:17)
    at async TestRunnerClient.runTest (/Users/tsuf/Documents/wing/libs/wingsdk/lib/shared-gcp/test-runner.inflight.js:32:41)
    at async runTestsWithRetry (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:224:28)
    at async withSpinner (/Users/tsuf/Documents/wing/apps/wing/dist/util.js:57:24)
    at async testTf (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:276:25)
    at async testFile (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:74:39)
    at async Promise.all (index 8)
    at async Object.test (/Users/tsuf/Documents/wing/apps/wing/dist/commands/test/test.js:93:5)
    at async Command.<anonymous> (/Users/tsuf/Documents/wing/apps/wing/dist/cli.js:51:30)
At bucket/metadata.test.w
runtime error: Resource root/Test.rtDXJoCrb8/env0/cloud.Bucket does not support inflight operation metadata (requested by root/Test.rtDXJoCrb8/env0/test:metadata()/Handler).
It might not be implemented yet.
  --> examples/tests/sdk_tests/bucket/metadata.test.w:5:19
  | 
  | let b = new cloud.Bucket();
  | 
5 | test "metadata()" {
  |                   ^
at _registerOnLift (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/metadata.test.w:5:19)
at (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/metadata.test.w:5:1)
At bucket/copy.test.w
runtime error: Resource root/Test.HGv9hMqVU5/env0/cloud.Bucket does not support inflight operation copy (requested by root/Test.HGv9hMqVU5/env0/test:copy()/Handler).
It might not be implemented yet.
  --> examples/tests/sdk_tests/bucket/copy.test.w:6:15
  | 
  | let b = new cloud.Bucket();
  | 
6 | test "copy()" {
  |               ^
at _registerOnLift (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/copy.test.w:6:15)
at (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/copy.test.w:6:1)
At bucket/events.test.w
runtime error: Resource "@winglang/sdk.cloud.Counter" is not yet implemented for "tf-gcp" target. Please refer to the roadmap https://github.com/orgs/winglang/projects/3/views/1?filterQuery=cloud.Counter
   --> examples/tests/sdk_tests/bucket/events.test.w:11:18
   | }
   | 
   | let b = new cloud.Bucket();
11 | let idsCounter = new cloud.Counter();
   |                  ^
at (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/events.test.w:11:18)
At bucket/signed_url.test.w
runtime error: Resource root/Test.cRQLAGQcvb/env0/testBucket does not support inflight operation signedUrl (requested by root/Test.cRQLAGQcvb/env0/test:signedUrl/Handler).
It might not be implemented yet.
  --> examples/tests/sdk_tests/bucket/signed_url.test.w:7:18
  | 
  | let testBucket = new cloud.Bucket(public: true) as "testBucket";
  | 
7 | test "signedUrl" {
  |                  ^
at _registerOnLift (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/signed_url.test.w:7:18)
at (/Users/tsuf/Documents/wing/examples/tests/sdk_tests/bucket/signed_url.test.w:7:1)
```

### I expected this:

to work.
The non-passing tests are:

- [ ]   bucket/delete.test.w
- [ ]   bucket/exists.test.w
- [ ]   bucket/try_get.test.w
- [ ]   bucket/put.test.w
- [ ]   bucket/put_json.test.w
- [ ]   bucket/bucket_list.test.w
- [ ]   bucket/public_url.test.w

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by garysassano**
## Checklist

Closes #4702
Closes #5235

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Comment by garysassano** [comment]
Bucket tests all working.
<details>
  <summary>Click to expand</summary>

  image
  image
  image
  image
  image
  image
  image
  image
  image
  image
  image
  image
  image
</details>

**Review by tsuf239 — COMMENTED** [review]
looks good overall, let me test it manually first :)

**Comment by tsuf239** [comment]
> Bucket tests all passing.
> 
> image

Awesome!

**Review by tsuf239 — APPROVED** [review]
Awesome!! 
all the possible tf-gcp tests pass locally!!!!!!!!
image
image

amazing job! 🥇

**Pull request merged**
