### PR TITLE
feat(console): allow collapsing and expanding nodes

### LINKED ISSUE #5187: feat(console): allow collapsing/expanding nodes

### PR DESCRIPTION
**Pull request by skyrpex**
Resolves #5187.

### CODE REVIEW

**Comment by eladb** [comment]
Any chance you can share a screen cast of this?

**Comment by skyrpex** [comment]
https://github.com/winglang/wing/assets/1077520/cecd5591-ef46-483e-809c-9b95c5dad247

@eladb

**Comment by skyrpex** [comment]
https://github.com/winglang/wing/assets/1077520/a0bced7f-adb8-4d24-a210-2c3ffcb59888

**Comment by eladb** [comment]
I am wondering if we can auto-zoom to the node being expanded. Basically I click on a node and it "fills" the screen, and I can see all the details inside it.

Also - what happened to the merging of connections? Didn't we say we wanted connections to merge?

**Pull request closed without merging**
