### PR TITLE
fix(compiler): bad error when compiling non-existent file

### PR DESCRIPTION
**Pull request by msalman-abid**
Changed `lib.rs` to no longer use the panic macro when a non-existent file is found, and instead throws an appropriate error using the `Diagnostic` struct. 

Example output:
```
Compilation failed with 1 errors
Error | Error reading source file: i_dont_exist.w: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
This should address the chore in [#1007](https://github.com/winglang/wing/issues/1007).

*By submitting this pull request, I confirm that my contribution is made under the terms of the 
[Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Comment by eladb** [comment]
@msalman-abid this is awesome! Thanks for looking into this.

I'll let @yoav-steinberg @MarkMcCulloh or @Chriscbr check this out!

**Comment by eladb** [comment]
Changed the title to reflect the bug being fixed instead of the solution (think changelog).

**Review by Chriscbr — APPROVED** [review]
LGTM! Thanks for the fix 🙏

**Comment by Chriscbr** [comment]
Hey @msalman-abid, I discovered we can't merge this code at the moment because of an issue with our CI/CD not working on forks (https://github.com/winglang/wing/issues/256) -- so for the time being, all code needs to be submitted through branches on the repo. If you'd like, you can request membership access through the link on our home page (https://www.winglang.io/), or I can submit a pull request with the same changes on your behalf - just let me know. Sorry for the inconvenience!

**Comment by msalman-abid** [comment]
Hi @Chriscbr, i've signed up for access. Considering that I would like to work on future contributions as well, this will be ideal. However, if this process takes too long (more than a few days), please feel free to merge this code on my behalf.
Cheers

**Comment by ShaiBer** [comment]
Hi Salman, I approved you now, so you should have a GitHub invite in your
inbox.

Thanks,
Shai

**Comment by msalman-abid** [comment]
Closing in favor of [#1063](https://github.com/winglang/wing/pull/1063)

**Pull request closed without merging**
