### PR TITLE
chore(docs): ci/cd guide

### LINKED ISSUE #2564: Ci/Cd Guide
https://www.winglang.io/docs/guides/ci-cd

### PR DESCRIPTION
**Pull request by skorfmann**
## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://www.winglang.io/terms-and-policies/contribution-license.html)*.

Closes #2564

### CODE REVIEW

**Comment by ekeren** [comment]
@skorfmann this is perfect!!!

**Review by ekeren — APPROVED** [review]

**Comment by MarkMcCulloh** [comment]
@Mergifyio refresh

**Comment by MarkMcCulloh** [comment]
@Mergifyio update

**Comment by MarkMcCulloh** [comment]
@Mergifyio backport main

**Pull request merged**
