### PR TITLE
chore(sdk): add tests for `std.Range`

### LINKED ISSUE #4229: range std tests

### PR DESCRIPTION
**Pull request by garysassano**
Closes #4229

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Comment by WeepingClown13** [comment]
@garysassano there is already #4281 fyi

**Comment by tsuf239** [comment]
it seems like @revitalbarletz had placed a [similar PR too ](https://github.com/winglang/wing/pull/4281) (I apologize for lack of coordination on our side!), I wouldn't mind having them both combined :)

**Comment by revitalbarletz** [comment]
Oh no, I haven't added myself as the assignee - just opened this issue. @garysassano let's work together, we have a working group of people that work together on std tests. I will add you to the group and we will continue there.

**Comment by garysassano** [comment]
Duplicate of #4281

**Pull request closed without merging**
