### PR TITLE
feat(console)!: use `simulator.update()`

### PR DESCRIPTION
**Pull request by skyrpex**
Closes https://github.com/winglang/wing/issues/6068

### CODE REVIEW

**Comment by skyrpex** [comment]
Started getting port-related errors when updating a wing project:

```
Error: connect ECONNREFUSED 127.0.0.1:64458
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 64458
}
Error: connect ECONNREFUSED 127.0.0.1:64458
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 64458
}
```

**Comment by skyrpex** [comment]
> Started getting port-related errors when updating a wing project:

I updated dependencies on the project I was getting the errors, are they just disappeared. Seems to be working fine.

**Comment by skyrpex** [comment]
@Chriscbr please, check it out 🙏🏻 

BTW, the `instance.update(simDir);` is misleading as it's expecting a simfile, like in `new simulator.Simulator({ simfile });`. Maybe we should rename it and check its docs?

**Comment by eladb** [comment]
> @Chriscbr please, check it out 🙏🏻 
> 
> 
> 
> BTW, the `instance.update(simDir);` is misleading as it's expecting a simfile, like in `new simulator.Simulator({ simfile });`. Maybe we should rename it and check its docs?

Feel free to update as part of this PR

**Comment by skyrpex** [comment]
> looks good.
> 
> is this covered by some test?

Nope, I'll have to think of a good test that covers this functionality...

**Comment by skyrpex** [comment]
Can't make the test pick up real time changes to wing files... Let's add a test later when we have some more time for this.

**Review by polamoros — APPROVED** [review]

**Pull request merged**
