### PR TITLE
chore(docs): changed title to "pulumi vs. wing [main differences]"

### PR DESCRIPTION
**Pull request by RoniWDS**
## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Review by hasanaburayyan — COMMENTED** [review]
Hey @RoniWDS 👋 Thanks for the suggested title change. I realize the file names say "vs" but Im wondering if that sends the wrong message. For instance I could imagine a world where Wing could have a target that leverages Pulumi (as it does with CDKTF and CDKAWS). Which makes me think that in the FAQ section for comparisons it might make sense to use "main differences" over "vs" 

But Im interested to hear from @ShaiBer on this one.

**Comment by ShaiBer** [comment]
The 'vs' is for SEO - to make it easier to find, but if it has a negative connotation and reduces the accuracy of the message then we will not use it

**Comment by ekeren** [comment]
I like `vs` , this is how I personally find solutions that compete with each other. I write in Google "pulumi vs" and it completes the competition 

Pulumi also likes `vs` 

https://www.pulumi.com/docs/concepts/vs/

https://www.pulumi.com/docs/concepts/vs/terraform/

**Comment by MarkMcCulloh** [comment]
I think going with `vs` makes sense even though I personally dislike the adversarial phrasing. One day when we support a pulumi target, the comparison for using wing as a solution vs pulumi as a solution is still valid. It's like comparing wing to terraform.

**Review by hasanaburayyan — APPROVED** [review]
Alright I think we have consensus on this change being worth it. So Im going to approve these PRs

**Pull request merged**
