### PR TITLE
chore(compiler): jsify in memory

### PR DESCRIPTION
**Pull request by Chriscbr**
Progress towards #2548 - this PR refactors the jsifier stage so that errors can be emitted without having to generate files.

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Comment by Chriscbr** [comment]
@MarkMcCulloh I wanted to add the jsify step to the LSP, but I ran into an issue since the main compiler expects an absolute project directory, but I wasn't sure if it's made available in the LSP. Do you know if there's a way to get this information?

**Review by eladb — APPROVED** [review]
LGTM, although I am not sure why emitting files is a Bad Thing™️

**Comment by Chriscbr** [comment]
@eladb When the LSP recompiles your code in the background, there shouldn't be any need for it to emit intermediate JS files (it would just slow it down). I think it's actually a really nice/clean separation of concerns

**Comment by MarkMcCulloh** [comment]
> there's also no harm in that

There is, fs operations have a cost that is effectively wasted in certain contexts. It also adds a new failure category (io error).

> at certain scale, keeping all of our output in-memory might actually be a problem and we will end up having to emit output files.

I think the true solution is that emitting shouldn't do any analysis and should only be responsible for emitting. That way this change wouldn't even have been needed in the first place because. I'm sure we'll get there at some point.

> compiler expects an absolute project directory, but I wasn't sure if it's made available in the LSP. Do you know if there's a way to get this information?

@Chriscbr iirc, the path of the wing file is absolute. So the "project directory" would be the directory of that file. We also have access to the root of the "workspace", the lsp provides that in the [initializer](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams) as well.

**Pull request merged**
