### PR TITLE
chore: remove unused jsii-rosetta

### PR DESCRIPTION
**Pull request by lausuarez02**
## Description
Update jsii-rosetta to avoid having deprecation

Resolves [4762](https://github.com/winglang/wing/issues/4762)
## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Docs updated (only required for features)
- [x] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Comment by lausuarez02** [comment]
I understand that the checks that are failing is because i'm updating the jsii-rosetta

**Comment by MarkMcCulloh** [comment]
Based on the failed action, updating jsii-rosetta will be harder than it seems.

A possible option here is to simply remove our dependency on jsii-rosetta. We don't actually use it in our version of jsii-docgen. 
The only reference is to an enum here https://github.com/winglang/wing/blob/main/apps/jsii-docgen/src/docgen/view/documentation.ts#L7

We can change this to a simple string instead, and just remove the dependency. @lausuarez02 Is that something you'd still be up for?

**Comment by lausuarez02** [comment]
Yup, i'm on it. I will upload another pr shortly

**Review by MarkMcCulloh — APPROVED** [review]

**Comment by staycoolcall911** [comment]
Nice, @lausuarez02 congrats on completing this one!

**Pull request merged**
