### PR TITLE
feat(sdk): add `Bucket.metadata()` for `tf-azure` target

### LINKED ISSUE #4333: Implement `cloud.Bucket` inflight method `metadata` for Azure target
```js
/**
 * Get the metadata of an object in the bucket.
 */
inflight metadata(key: str): ObjectMetadata;

/**
 * Metadata of a bucket object.
 */
struct ObjectMetadata {
  /** The size of the object in bytes. */
  size: num;
  /** The time the object was last modified. */
  lastModified: Datetime;
  /** The content type of the object, if it is known. */
  contentType: str?;
}
```

### PR DESCRIPTION
**Pull request by garysassano**
Closes #4333

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Review by tsuf239 — COMMENTED** [review]
looks good, can you please add metadata to the azure's `bucket.supportedOps` ?

**Comment by tsuf239** [comment]
Can you please merge in main?

**Comment by garysassano** [comment]
Tested to work in Azure.

**Comment by garysassano** [comment]
Tested to work on Azure.

**Review by tsuf239 — APPROVED** [review]
Great Work!

**Pull request merged**
