### PR TITLE
chore(repo): update contributors section of readme

### PR DESCRIPTION
**Pull request by jakepage91**
- I have removed the previous contributors html code. 
- The implementation I have added used [contrib.rocks](https://contrib.rocks/preview?repo=winglang%2Fwing) to read the latest list on commits, extracting the resulting contributors and adding their avatars to the list. The list will update ever time there is a new merge to main.  
- I have kept the same amount of columns across which was 7 but this can be easily changed by editing the `&columns=7` flag. 

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Comment by jakepage91** [comment]
I'm not sure what you are going to want to do with the `.all-contributorsrc` file since it is not needed anymore. If you want me to remove it, just say the word.

**Comment by Chriscbr** [comment]
@jakepage91 Yes let's remove the `.all-contributorsrc` file

Also we can take out these dependency and scripts from the `package.json` file (at the root) pertaining to the old contributors tool.

**Comment by jakepage91** [comment]
Done @Chriscbr 👍

**Review by Chriscbr — APPROVED** [review]
thanks!

**Pull request merged**
