### PR TITLE
fix(sdk): remove /{proxy+} from path and add OPTIONS

### PR DESCRIPTION
**Pull request by meirdev**
Fix for: #5210

Add OPTIONS method instead of default handler with `{proxy+}`.

I can't write a _real_ test because I depend on how aws responds to changes, so I tried with small code:

```wing
bring cloud;

let api = new cloud.Api(cors: true);

api.get("/:id", inflight (req) => {
    let id = req.vars.get("id");

    return {
        body: "get id: {id}",
        status: 200,
    };
});

api.post("/:id", inflight (req) => {
    let id = req.vars.get("id");

    return {
        body: "post id: {id}",
        status: 200,
    };
});
```

```html
<html>
  <head>
    <script>
      fetch(
        "https://amol7a6ij3.execute-api.us-east-1.amazonaws.com/prod/page-id",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: "test",
        }
      ).then((res) => {
        res.text().then((data) => {
          console.log(data);
        });
      });
    </script>
  </head>

  <body>
  </body>
</html>
```

You can see the OPTIONS request that was sent when I entered the page:

Screenshot 2023-12-21 at 9 55 18

### CODE REVIEW

**Review by eladb — APPROVED** [review]
👏

**Comment by staycoolcall911** [comment]
@meirdev - can you please resolve the conflicts on this PR? It should then merge automatically

**Comment by yoav-steinberg** [comment]
@meirdev I reverted this since this fails on aws:

`apps/wing/bin/wing test -t tf-aws examples/tests/sdk_tests/api/404.test.w`

If you need help recreating it on AWS try to ping me on slack.

**Comment by staycoolcall911** [comment]
@meirdev just to add some more details on why your PR was reverted:
First off, this is completely not your fault as a contributor. It's on us to improve our process.

We have a full test suite under `examples/tests/sdk_tests` which runs wing on the local simulator as well as on the cloud, to verify functional alignment between all platforms supported by wing (e.g. `sim`, `tf-aws`, etc.). 
Currently these tests run post merge to `main` and the one indicated by Yoav failed.
Please let us know if you have any questions on how to fix this test. Thank you!

**Comment by meirdev** [comment]
It's OK,

The problem is in the difference between the AWS and the simulator, in AWS they return a 403 by default and the simulator returns a 404.

My fix allows the user to set what they choose (the default with the `{proxy+}` caused the problem I mentioned in the issue).

Should I change the simulator that will return 403 or delete the test, (or my fix)?

**Comment by tsuf239** [comment]
@meirdev, thanks for your contribution! 
we should always aim to match the behaviour between the sim and the cloud platforms :) 
so, 
- we should keep the test!
- if it makes sense to return 403 ("access to the requested resource is forbidden") we should change the simulator too- in this case I suspect it happens because of missing permissions (but I admit I haven't checked closely... ), so I guess checking that would be the first step :)

**Comment by meirdev** [comment]
@tsuf239 API Gateway REST API returns "Missing Authentication Token" (403) in our case because "The API request is made to an operation or resource that doesn't exist" ([source](https://repost.aws/knowledge-center/api-gateway-authentication-token-errors)).

I can change the test from 404 to 403, and change `libs/wingsdk/src/target-sim/api.inflight.ts`:

```typescript
  public async addEventSubscription(
    subscriber: string,
    subscriptionProps: EventSubscription
  ): Promise<void> {
    const routes = (subscriptionProps as any).routes as ApiRoute[];
    routes.forEach((r) => {
      const s = {
        functionHandle: subscriber,
        method: r.method,
        path: r.path,
      };
      this.routes.push(s);
      this.populateRoute(s, subscriber);
    });

    // return 403 by default (as AWS does)
    this.app.use(async (
      req: express.Request,
      res: express.Response,
    ) => {
      req;
      res.sendStatus(403);
    });
  }
```

**Comment by tsuf239** [comment]
@meirdev I see. 
It looks like it happens because of not using `API_CORS_DEFAULT_RESPONSE` anymore, is it possible to change it back? (in a way it'll include your change while preserving the 404 response?)
if needed, you can maybe ask @skorfmann for help :)

**Comment by meirdev** [comment]
I found a solution, it is possible to change the responses of the error pages:

```typescript
/**
 * Custom error when the resource doesn't exist
 */
const GATEWAY_404_RESPONSE = {
  "x-amazon-apigateway-gateway-responses": {
    "MISSING_AUTHENTICATION_TOKEN": {
      "statusCode": "404",
      "responseTemplates": {
        "application/json": "{\"message\": $context.error.messageString }",
      },
    },
  }
}

class WingRestApi extends Construct {
...
  
    constructor(
...
    ) {
...
              return {
                ...openApiSpec,
                ...GATEWAY_404_RESPONSE,
              }
...
      });
```

**Comment by tsuf239** [comment]
@meirdev looks good :) 
Can you please open a new PR with the fix?

**Pull request merged**
