### PR TITLE
chore(sdk): switch function log format from `text` to `JSON` for AWS platforms

### PR DESCRIPTION
**Pull request by garysassano**
A best practice when authoring Lambda functions is to use the Powertools for AWS Lambda [Logger](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/), which allows to emit structured logs in JSON format. However, even if you choose not to use Powertools, you can still take advantage of the JSON format to make navigating through your functions' logs much easier. This is true especially for the system logs, over which you have no direct control.

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Comment by tsuf239** [comment]
@Chriscbr what do you think?

**Comment by Chriscbr** [comment]
It sounds handy, let's try it 👍

**Comment by tsuf239** [comment]
Hi @garysassano,
Can you please resolve the conflicts? 
(you can accept incoming changes, and let the PR actions fix them)

**Comment by tsuf239** [comment]
I started an automated test on aws [here](https://github.com/winglang/wing/actions/runs/8409734177)

**Comment by tsuf239** [comment]
The automated aws tests are failing: https://github.com/winglang/wing/pull/5955#issuecomment-2016814275
I'm not sure, but it seems like this PR caused it indirectly- and that a fix is needed at our end 
@MarkMcCulloh what do you think?

**Comment by tsuf239** [comment]
Hi @garysassano, can you please update from main?

**Comment by tsuf239** [comment]
@garysassano math doesn't seem to work on AWS, can you please check? https://github.com/winglang/wing/actions/runs/8866141232/job/24343706916
(also, it doesn't pass mutation)

**Comment by garysassano** [comment]
I opened issue #6363, it should be fine once it gets fixed.

**Comment by tsuf239** [comment]
Sdk spec tests are successful on [tf-aws](https://github.com/winglang/wing/actions/runs/9092085739/job/24988049927)! 
🤩 

it can be merged as soon as you'll fix the pr action

**Review by tsuf239 — APPROVED** [review]

**Comment by tsuf239** [comment]
Hi @garysassano do you need any help?

**Comment by tsuf239** [comment]
tests passed again: https://github.com/winglang/wing/actions/runs/9790966100

**Comment by tsuf239** [comment]
Well done @garysassano!!! 🏆 🎉🥳🎉👏👏👏

**Comment by revitalbarletz** [comment]
Well done @garysassano !

**Pull request merged**
