### PR TITLE
chore: use token for self-mutation workflow

### LINKED ISSUE #1178: self-mutation workflow unexpected behavior
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Created a PR, self-mutation workflow ran and pushed a commit

### I expected this:

a new "build" workflow to be triggered on the new commit

### Instead, this happened:

No new build was trigger, stalling the PR.
Also, it is jarring for the self-mutation workflow to fail when the new update is pushed.

### Component:

Contributor Experience

### Wing Version:

_No response_

### Node.js Version:

_No response_

### Platform(s):

_No response_

### Anything else?

example commit https://github.com/winglang/wing/pull/1162/commits/4355ff0536e10405d31f3e9b12ca63c78a59a688 on pr https://github.com/winglang/wing/pull/1162

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
I couldn't figure out a way around this, we will unfortunately require users in forks to set their own token for the self-mutation workflow.

Fixes #1178

*By submitting this pull request, I confirm that my contribution is made under the terms of the 
[Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Comment by hasanaburayyan** [comment]
Since we need to have the users set their own tokens for self mutations maybe this PR should have a contributor's docs update as well?

**Comment by eladb** [comment]
@Chriscbr do you recall if we ever solved this in projen? I vaguely recall that we dealt with it somehow.

**Comment by Chriscbr** [comment]
Mmm I'm not sure - I think self mutation simply didn't work on forks.

**Comment by eladb** [comment]
> Mmm I'm not sure - I think self mutation simply didn't work on forks.

That's entirely possible

**Comment by MarkMcCulloh** [comment]
Interestingly, the self-mutation we have does work in the sense that it updated the branch. The problem was only that GH did not trigger any new builds on the new commit because it was caused by the "github action" user.

**Review by eladb — APPROVED** [review]

**Pull request merged**
