### PR TITLE
chore(compiler): add clippy lints

### PR DESCRIPTION
**Pull request by Chriscbr**
Add some more lints to our rust projects to make our code cleaner / more idiomatic. Most of the lints seemed straightforward (removing unneeded clones and dereferences etc.) but any of them can be turned off or selectively disabled if they seem obnoxious.

Also removed some unused dependencies.

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Comment by eladb** [comment]
Ok if we hold off with this one. I am working on converting all of the code in jsify.rs to `CodeMaker` and this will make my life a living hell...

(changed to draft)

**Review by staycoolcall911 — COMMENTED** [review]
I love this cleanup, thank you! Now that #2045 is merged - I think you can resume this PR - looks like removing serde sub module led to some build issues

**Comment by MarkMcCulloh** [comment]
Nice, were these auto-fixable lints?

**Comment by Chriscbr** [comment]
> Nice, were these auto-fixable lints?

Yep, I think almost all of them were auto-fixed, except for a few like "your function is returning a crazy complex type, please simplify it" which I just created type alias to fix

**Review by MarkMcCulloh — APPROVED** [review]

**Comment by Chriscbr** [comment]
@mergifyio refresh

**Pull request merged**
